### ISSUE TITLE
VIEW (view.js)에서 상태 변경이 잘 안되는 이슈

### ISSUE THREAD

**Issue by ksa37** [di-uni/CS492_Team4_Web_SSR_with_Server_Driven_UI#37]
view.js 3가지 뷰의 종류별로 각 태그에 대한 값을 갖도록 useState를 통해 구현을 했습니다.
하지만 3가지 각각의 뷰의 태그 상태 변경이 바로 안되어 화면 전환이 잘 안됩니다.
이 밑의 태그들을 구현한 것이
<img width="767" alt="스크린샷 2021-12-03 오후 1 59 48" src="https://user-images.githubusercontent.com/41234227/144547956-f968ca66-ea97-46a0-aeb0-38f89e0d1f96.png">

이 코드이고 여기서 아래와 같은setViewTag라는 함수를 사용하여 각 view 옵션이 갖는 태그 값을 변경합니다.
<img width="962" alt="스크린샷 2021-12-03 오후 1 56 15" src="https://user-images.githubusercontent.com/41234227/144547619-de510c22-b4e5-4af7-b0d3-007979521d38.png">

그런데 이 setViewTag에서 콘솔을 찍어본 결과 바로 currentBasicTag등이 반영이 안되고 다른 액션을 취한 뒤에 반영이 되는 것을 확인했습니다.
<img width="1016" alt="스크린샷 2021-12-03 오후 1 56 27" src="https://user-images.githubusercontent.com/41234227/144547639-66bd3fa0-ee10-463f-8f29-a4d9e673f80e.png">

아래는 각 상태값에 따라 달라지는 화면을 구현한 것인데 너무 naive하게 짠것은 아닐지, 아니면 이때문에 반영이 잘 안되는 것일지 모르겠습니다.
<img width="1006" alt="스크린샷 2021-12-03 오후 1 56 39" src="https://user-images.githubusercontent.com/41234227/144547663-8e898057-8134-4d71-b533-1b7eedc12e61.png">

**Comment by weumj** [comment]
질문답변 시간에 문의주신 내용 추가로 확인해서 답변드리자면
viewType이 0인 경우, 다양한 basicTag에 대한 처리가 누락되어 있어서 그런것 같습니다.

https://github.com/di-uni/CS492_Team4_Web_SSR_with_Server_Driven_UI/blob/feature/ui_view/render_server/src/components/view.js#L193-L197

**Comment by ksa37** [comment]
> 질문답변 시간에 문의주신 내용 추가로 확인해서 답변드리자면 viewType이 0인 경우, 다양한 basicTag에 대한 처리가 누락되어 있어서 그런것 같습니다.
> 
> https://github.com/di-uni/CS492_Team4_Web_SSR_with_Server_Driven_UI/blob/feature/ui_view/render_server/src/components/view.js#L193-L197

코드 확인 감사드립니다!! 이 부분 확인했고 그 때 추천해주신 switch문과 array 활용해서 더 간단하게 코드 수정 완료해서 해결했습니다. 감사합니다:)
